from .payment_view import PaymentRequestView, PaymentHistoryView
from .zarinpal_callback_view import ZarinpalCallbackView
from .paydotir_callback_veiw import PaydotirCallbackView
from .bank_card_view import BankCardView
from .withdraw_view import WithdrawRequestView, WithdrawHistoryView
from .bank_account_view import BankAccountView
from .zibal_callback_view import ZibalCallbackView
from .proxy_redirect_view import ProxyPaymentRedirectView
from .jibit_callback_view import JibitCallbackView
from .gateway_info_view import GatewayInfoView
