# Generated by Django 4.0 on 2022-07-09 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0104_network_need_memo_transfer_memo'),
        ('accounts', '0063_alter_externalnotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=12)),
                ('enable', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='StakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('process', 'process'), ('pending', 'pending'), (' done', ' done'), ('cancel_process', 'cancel_process'), ('cancel_pending', 'cancel_pending'), ('cancel_cancel', 'cancel_cancel')], max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('stake_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stake.stakeoption')),
            ],
        ),
        migrations.CreateModel(
            name='StakeRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('revenue', models.DecimalField(decimal_places=6, max_digits=12)),
                ('stake_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stake.stakerequest')),
            ],
            options={
                'unique_together': {('created', 'stake_request')},
            },
        ),
    ]
