# Generated by Django 4.0 on 2022-07-26 14:42

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0003_remove_stakeoption__yield_stakeoption_apr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakerequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stakerequest',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
