# Generated by Django 4.0 on 2022-07-27 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0004_alter_stakerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakerevenue',
            name='revenue',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
