# Generated by Django 4.1.3 on 2023-07-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0012_stakerequest_is_bot'),
        ('stake', '0012_stakerequest_login_activity'),
    ]

    operations = [
    ]
