# Generated by Django 4.1.3 on 2023-12-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0015_alter_stakeoption_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeoption',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='stakeoption',
            name='type',
            field=models.CharField(choices=[('defi', 'defi'), ('stake', 'stake'), ('bot', 'bot')], default='defi', max_length=6),
        ),
    ]
