# Generated by Django 4.1.3 on 2023-12-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0016_alter_stakerevenue_created'),
        ('stake', '0016_remove_stakeoption_is_bot_stakeoption_type'),
    ]

    operations = [
    ]
