# Generated by Django 4.0 on 2021-12-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_user_user_email_verification_date_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account'),
        ),
    ]
