# Generated by Django 4.0 on 2021-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='coin',
            new_name='symbol',
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.FileField(default='', upload_to='asset-logo/'),
            preserve_default=False,
        ),
    ]
