# Generated by Django 4.0 on 2022-01-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_coin_asset_symbol_asset_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='network',
        ),
        migrations.AddField(
            model_name='network',
            name='symbol',
            field=models.CharField(db_index=True, default='', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='ledger.wallet'),
        ),
    ]
