# Generated by Django 4.0 on 2022-01-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_network_network_network_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
