# Generated by Django 4.0 on 2022-01-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_network_can_withdraw'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkwallet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='networkwallet',
            name='network',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ledger.network'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='networkwallet',
            unique_together={('network', 'wallet')},
        ),
        migrations.RemoveField(
            model_name='networkwallet',
            name='network_asset',
        ),
    ]
