# Generated by Django 4.0 on 2022-01-01 12:12

from django.db import migrations, models
import django.db.models.deletion
import ledger.utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('ledger', '0005_alter_networkwallet_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(db_index=True, default=ledger.utils.random.secure_uuid4)),
                ('price', models.DecimalField(decimal_places=18, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('dest_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_otc', to='ledger.asset')),
                ('src_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_otc', to='ledger.asset')),
            ],
        ),
    ]
