# Generated by Django 4.0 on 2022-01-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('ledger', '0027_alter_marginloan_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='secret',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='wallet.secret'),
            preserve_default=False,
        ),
    ]
