# Generated by Django 4.0 on 2022-01-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_last_margin_warn'),
        ('wallet', '0002_rename_key_secret_encrypted_key'),
        ('ledger', '0028_depositaddress_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='schema',
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='network',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='ledger.network'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', unique=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.secret')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='account_secret',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='ledger.accountsecret'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('network', 'account_secret')},
        ),
        migrations.RemoveField(
            model_name='depositaddress',
            name='account',
        ),
        migrations.RemoveField(
            model_name='depositaddress',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='depositaddress',
            name='secret',
        ),
        migrations.DeleteModel(
            name='AddressSchema',
        ),
    ]
