# Generated by Django 4.0 on 2022-02-19 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0053_alter_transfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='withdraw_step',
        ),
        migrations.AddField(
            model_name='networkasset',
            name='withdraw_step',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
