# Generated by Django 4.0 on 2022-03-16 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_level_2_prize_activate_mood_historicaluser_level_2_prize_activate_and_more'),
        ('ledger', '0065_alter_asset_ask_diff_alter_asset_bid_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('p', 'prize')], max_length=1),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('scope', models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('sign_up_prize', 'sign_up_prize'), ('first_trade_price', 'first_trade_price')], max_length=25)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
            options={
                'unique_together': {('account', 'scope')},
            },
        ),
    ]
