# Generated by Django 4.0 on 2022-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_alter_trx_scope_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('sign_up', 'sign_up'), ('first_trade_price', 'first_trade_price')], max_length=25),
        ),
    ]
