# Generated by Django 4.0 on 2022-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_historicaluser_first_trade_prize_activate_and_more'),
        ('ledger', '0067_alter_prize_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('level 2 verification', 'level 2 verification'), ('sign up', 'sign up'), ('first trade', 'first trade')], max_length=25, verbose_name='نوع'),
        ),
    ]
