# Generated by Django 4.0 on 2022-03-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_alter_addressbook_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='asset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset'),
        ),
    ]
