# Generated by Django 4.0 on 2022-04-06 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_historicaluser_first_trade_prize_activate_and_more'),
        ('ledger', '0069_merge_20220406_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'verbose_name': 'دفترچه آدرس\u200cها', 'verbose_name_plural': 'دفترچه\u200cهای آدرس'},
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='address',
            field=models.CharField(max_length=100, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.asset', verbose_name='رمزارز'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network', verbose_name='شبکه'),
        ),
        migrations.AlterField(
            model_name='trx',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('f', 'transfer'), ('m', 'margin transfer'), ('b', 'margin borrow'), ('c', 'commission'), ('l', 'liquid'), ('fl', 'fast liquid'), ('p', 'prize')], max_length=2),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('scope', models.CharField(choices=[('level 2 verification', 'level 2 verification'), ('sign up', 'sign up'), ('first trade', 'first trade')], max_length=25, verbose_name='نوع')),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='کاربر')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
            options={
                'unique_together': {('account', 'scope')},
            },
        ),
    ]
