# Generated by Django 4.0 on 2022-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0069_alter_addressbook_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='address',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
