# Generated by Django 4.0 on 2022-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0071_alter_addressbook_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
