# Generated by Django 4.0 on 2022-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0079_prize_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='fake',
        ),
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('level2_verify', 'level2_verify'), ('signup', 'signup'), ('first_trade', 'first_trade')], max_length=25, verbose_name='نوع'),
        ),
    ]
