# Generated by Django 4.0 on 2022-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0080_remove_prize_fake_alter_prize_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('trade_2m', 'trade_2m')], max_length=25, verbose_name='نوع'),
        ),
    ]
