# Generated by Django 4.0 on 2022-05-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0081_prize_fake_alter_prize_scope'),
        ('ledger', '0082_alter_networkasset_withdraw_fee_and_more'),
    ]

    operations = [
    ]
