# Generated by Django 4.0 on 2022-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0083_merge_20220514_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='scope',
            field=models.CharField(choices=[('trade_2m', 'trade_2m'), ('referral_trade_2m', 'referral_trade_2m')], max_length=25, verbose_name='نوع'),
        ),
    ]
