# Generated by Django 4.0 on 2022-06-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0091_merge_0089_alter_trx_scope_0090_margintransfer_asset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('network', 'address')},
        ),
        migrations.RemoveField(
            model_name='depositaddress',
            name='account_secret',
        ),
        migrations.DeleteModel(
            name='AccountSecret',
        ),
    ]
