# Generated by Django 4.0 on 2022-06-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0093_depositaddress_created_depositaddress_is_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='address_key',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='ledger.addresskey'),
            preserve_default=False,
        ),
    ]
