# Generated by Django 4.0 on 2022-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0096_remove_asset_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='kucoin_withdraw_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(choices=[('kucoin-spot', 'kucoin-spot'), ('kucoin-feature', 'kucoin-feature'), ('binance-spot', 'binance-spot'), ('binance-future', 'binance-future')], default='binance-future', max_length=32),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('binance_interface', 'binance_interface'), ('kucoin_interface', 'kucoin_interface')], default='self', max_length=32),
        ),
    ]
