# Generated by Django 4.0 on 2022-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0097_networkasset_kucoin_withdraw_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(choices=[('kucoin_spot', 'kucoin_spot'), ('kucoin_feature', 'kucoin_feature'), ('binance_spot', 'binance_spot'), ('binance_future', 'binance_future')], default='binance_future', max_length=32),
        ),
    ]
