# Generated by Django 4.0 on 2022-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0098_alter_asset_hedge_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(choices=[('kucoin-spot', 'kucoin-spot'), ('kucoin-feature', 'kucoin-feature'), ('binance-spot', 'binance-spot'), ('binance-future', 'binance-future')], default='binance-future', max_length=32),
        ),
    ]
