# Generated by Django 4.0 on 2022-06-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0097_networkasset_kucoin_withdraw_enable_and_more'),
        ('ledger', '0099_remove_trx_check_ledger_trx_amount_and_more'),
    ]

    operations = [
    ]
