# Generated by Django 4.0 on 2022-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0100_closerequest_balancelock_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelock',
            name='reason',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
