# Generated by Django 4.0 on 2022-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0100_merge_20220625_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='hedger_withdraw_enable',
            field=models.BooleanField(default=True),
        ),
    ]
