# Generated by Django 4.0 on 2022-06-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_networkasset_hedger_withdraw_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkasset',
            name='binance_withdraw_enable',
        ),
        migrations.RemoveField(
            model_name='networkasset',
            name='kucoin_withdraw_enable',
        ),
    ]
