# Generated by Django 4.0 on 2022-06-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_asset_new_coin'),
        ('ledger', '0101_balancelock_reason'),
    ]

    operations = [
    ]
