# Generated by Django 4.0 on 2022-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_balancelock_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkasset',
            old_name='binance_withdraw_enable',
            new_name='hedger_withdraw_enable',
        ),
        migrations.AlterField(
            model_name='asset',
            name='hedge_method',
            field=models.CharField(choices=[('kucoin-spot', 'kucoin-spot'), ('kucoin-future', 'kucoin-future'), ('binance-spot', 'binance-spot'), ('binance-future', 'binance-future'), ('', '')], default='binance-future', max_length=32),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('binance', 'binance'), ('kucoin', 'kucoin')], default='self', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='closerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'new')), fields=('account',), name='unique_margin_close_request_account'),
        ),
    ]
