# Generated by Django 4.0 on 2022-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0102_merge_0101_asset_new_coin_0101_balancelock_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='name_fa',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='closerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'new')), fields=('account',), name='unique_margin_close_request_account'),
        ),
    ]
