# Generated by Django 4.0 on 2022-06-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_balancelock_reason'),
        ('ledger', '0102_remove_networkasset_binance_withdraw_enable_and_more'),
    ]

    operations = [
    ]
