# Generated by Django 4.0 on 2022-07-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0094_depositaddress_address_key'),
        ('ledger', '0104_network_need_memo_transfer_memo'),
    ]

    operations = [
    ]
