# Generated by Django 4.0 on 2022-07-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_customtoken_options_remove_customtoken_created_and_more'),
        ('ledger', '0104_network_need_memo_transfer_memo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together={('network', 'address')},
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AddressKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'address')},
            },
        ),
        migrations.RemoveField(
            model_name='depositaddress',
            name='account_secret',
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='address_key',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='ledger.addresskey'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountSecret',
        ),
    ]
