# Generated by Django 4.0 on 2022-07-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0105_alter_depositaddress_unique_together_and_more'),
        ('ledger', '0105_alter_margintransfer_amount'),
    ]

    operations = [
    ]
