# Generated by Django 4.0 on 2022-07-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0106_merge_20220716_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositaddress',
            name='account_secret',
        ),
    ]
