# Generated by Django 4.0 on 2022-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0107_remove_depositaddress_account_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='can_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
