# Generated by Django 4.0 on 2022-07-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0108_networkasset_can_deposit_delete_accountsecret'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cryptobalance',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='AccountSecret',
        ),
        migrations.RemoveField(
            model_name='cryptobalance',
            name='deposit_address',
        ),
    ]
