# Generated by Django 4.0 on 2022-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0118_merge_20220815_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='kucoin_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('binance', 'binance'), ('kucoin', 'kucoin')], default='self', max_length=8),
        ),
    ]
