# Generated by Django 4.0 on 2022-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0118_merge_20220814_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='kucoin_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('binance', 'binance'), ('kucoin', 'kucoin')], default='self', max_length=8),
        ),
    ]
