# Generated by Django 4.0 on 2022-08-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0119_alter_transfer_source'),
        ('ledger', '0119_network_kucoin_name_alter_asset_symbol_and_more'),
    ]

    operations = [
    ]
