# Generated by Django 4.0 on 2022-08-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0119_network_kucoin_name_alter_transfer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
