# Generated by Django 4.0 on 2022-08-30 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_finotechrequest_weight'),
        ('financial', '0057_auto_20220822_1719'),
        ('ledger', '0128_asset_original_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastBuyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.paymentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر')),
            ],
        ),
    ]
