# Generated by Django 4.0 on 2022-08-29 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0129_fastbuytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastbuytoken',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
