# Generated by Django 4.0 on 2022-08-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0057_auto_20220822_1719'),
        ('ledger', '0129_fastbuytoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fastbuytoken',
            options={'verbose_name': 'خرید سریع رمزارز', 'verbose_name_plural': 'خرید سریع رمزارز'},
        ),
        migrations.AlterField(
            model_name='fastbuytoken',
            name='payment_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial.paymentrequest'),
        ),
    ]
