# Generated by Django 4.0 on 2022-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0130_alter_fastbuytoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastbuytoken',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('deposit', 'deposit'), ('done', 'done')], default='process', max_length=16),
        ),
    ]
