# Generated by Django 4.0 on 2022-08-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0131_fastbuytoken_status'),
        ('ledger', '0131_systemsnapshot_kucoin_spot_systemsnapshot_mexc_spot'),
    ]

    operations = [
    ]
