# Generated by Django 4.0 on 2022-09-03 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_finotechrequest_weight'),
        ('financial', '0058_fiathedgetrx'),
        ('ledger', '0131_systemsnapshot_kucoin_spot_systemsnapshot_mexc_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastBuyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('process', 'process'), ('deposit', 'deposit'), ('done', 'done')], default='process', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial.paymentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید سریع رمزارز',
                'verbose_name_plural': 'خرید سریع رمزارز',
            },
        ),
    ]
