# Generated by Django 4.0 on 2022-09-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0132_fastbuytoken'),
        ('ledger', '0133_merge_20220831_1216'),
    ]

    operations = [
    ]
