# Generated by Django 4.0 on 2022-09-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0134_fastbuytoken'),
        ('ledger', '0134_merge_20220831_1858'),
    ]

    operations = [
    ]
