# Generated by Django 4.0 on 2022-09-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0134_merge_0132_fastbuytoken_0133_merge_20220831_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastbuytoken',
            name='otc_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.otcrequest'),
        ),
    ]
