# Generated by Django 4.0 on 2022-09-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0135_systemsnapshot_verified'),
        ('ledger', '0136_systemsnapshot_verified'),
    ]

    operations = [
    ]
