# Generated by Django 4.0 on 2022-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0137_merge_20220904_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastbuytoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='fastbuytoken',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
