# Generated by Django 4.0 on 2022-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0139_alter_prize_unique_together_prize_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hedge_method',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='provider_transfer',
        ),
        migrations.AddField(
            model_name='asset',
            name='hedge',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('provider', 'provider')], default='self', max_length=8),
        ),
    ]
