# Generated by Django 4.0 on 2022-10-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0140_remove_asset_candidate'),
        ('ledger', '0140_remove_asset_hedge_method_and_more'),
    ]

    operations = [
    ]
