# Generated by Django 4.0 on 2022-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0141_alter_asset_hedge_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkasset',
            name='hedger_deposit_enable',
            field=models.BooleanField(default=True),
        ),
    ]
