# Generated by Django 4.0 on 2022-11-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0141_alter_asset_hedge_method'),
        ('ledger', '0141_merge_20221026_1601'),
    ]

    operations = [
    ]
