# Generated by Django 4.0 on 2022-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0142_networkasset_hedger_deposit_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.CharField(choices=[('self', 'self'), ('internal', 'internal'), ('binance', 'binance'), ('kucoin', 'kucoin'), ('nobitex', 'nobitex')], default='self', max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('process', 'process'), ('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], db_index=True, default='process', max_length=8),
        ),
    ]
