# Generated by Django 4.1.3 on 2023-01-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0155_alter_marketspread_spread'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketspread',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('side', 'step'), name='market_spread_uniqueness_for_null_category'),
        ),
    ]
