# Generated by Django 4.1.3 on 2023-01-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0156_marketspread_market_spread_uniqueness_for_null_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetspreadcategory',
            options={'verbose_name': 'Spread Category', 'verbose_name_plural': 'Spread Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryspread',
            options={'verbose_name': 'Asset Spread', 'verbose_name_plural': 'Asset Spread'},
        ),
        migrations.AlterModelOptions(
            name='marketspread',
            options={'verbose_name': 'Market Spread', 'verbose_name_plural': 'Market Spread'},
        ),
    ]
