# Generated by Django 4.1.3 on 2023-02-07 20:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_historicaluser_first_crypto_deposit_date_and_more'),
        ('market', '0042_remove_trade_gap_revenue_remove_trade_hedge_price_and_more'),
        ('ledger', '0161_systemsnapshot_reserved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otcrequest',
            name='check_ledger_otc_request_amounts',
        ),

        migrations.AddField(
            model_name='otcrequest',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='base_irt_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30,
                                      validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='side',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='symbol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.pairsymbol'),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='asset',
            name='max_trade_quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='min_trade_quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='trade_quantity_step',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price_absolute_irt',
        ),
        migrations.RemoveField(
            model_name='otcrequest',
            name='to_price_absolute_usdt',
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='from_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('margin', 'margin'), ('loan', 'loan'), ('stake', 'stake'), ('voucher', 'voucher'), ('debt', 'debt')], max_length=8),
        ),
        migrations.AlterField(
            model_name='otcrequest',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otctrade',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done'), ('revert', 'revert')], default='pending', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='otcrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_amount__gte', 0), ('to_amount__gte', 0)), name='check_ledger_otc_request_amounts'),
        ),
    ]
