# Generated by Django 4.1.3 on 2023-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0162_remove_otcrequest_check_ledger_otc_request_amounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otctrade',
            name='execution_type',
            field=models.CharField(choices=[('m', 'market'), ('p', 'provider')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
