# Generated by Django 4.1.3 on 2023-02-08 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0163_otctrade_execution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcrequest',
            name='fee_usdt_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='otcrequest',
            constraint=models.CheckConstraint(
                check=models.Q(('amount__gte', 0), ('fee_amount__gte', 0), ('price__gte', 0)),
                name='otc_request_check_trade_amounts'),
        ),
    ]
