# Generated by Django 4.1.3 on 2023-02-08 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0164_otcrequest_fee_amount_otcrequest_fee_usdt_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcrequest',
            name='fee_revenue',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
