# Generated by Django 4.1.3 on 2023-02-08 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0165_otcrequest_fee_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='otctrade',
            name='gap_revenue',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='otctrade',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
