# Generated by Django 4.1.3 on 2023-03-11 13:38

from django.db import migrations, models


def quantify_multiplier(apps, sch):
    Asset = apps.get_model('ledger', 'Asset')
    for asset in Asset.objects.all():
        if asset.symbol.startswith('1M-'):
            asset.coin_multiplier = 1000000
            asset.save(update_fields=['coin_multiplier'])
        elif asset.symbol.startswith('1000'):
            asset.coin_multiplier = 1000
            asset.save(update_fields=['coin_multiplier'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0175_alter_closerequest_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coin_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(quantify_multiplier, reverse_code=migrations.RunPython.noop)
    ]
