# Generated by Django 4.1.3 on 2023-03-01 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0175_alter_closerequest_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcrequest',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=20, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
