# Generated by Django 4.1.3 on 2023-08-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0199_merge_20230802_1535'),
        ('ledger', '0200_alter_asset_spread_category_and_more'),
    ]

    operations = [
    ]
