# Generated by Django 4.1.3 on 2023-08-08 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0201_alter_wallet_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pricetracking',
            index=models.Index(fields=['user', 'asset'], name='price_tracking_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetracking',
            unique_together={('user', 'asset')},
        ),
    ]
