# Generated by Django 4.1.3 on 2023-08-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0201_alter_wallet_variant'),
        ('ledger', '0201_merge_20230807_1140'),
    ]

    operations = [
    ]
