# Generated by Django 4.1.3 on 2023-08-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0199_otctrade_hedged_otctrade_to_buy_amount'),
        ('ledger', '0201_alter_wallet_variant'),
    ]

    operations = [
    ]
