# Generated by Django 4.1.3 on 2023-08-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0202_merge_20230808_1416'),
        ('ledger', '0202_merge_20230812_1701'),
        ('ledger', '0203_manualtrade'),
    ]

    operations = [
    ]
