# Generated by Django 4.1.3 on 2023-08-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0204_merge_20230815_1211'),
        ('ledger', '0208_remove_asset_price_precision_irt_and_more'),
    ]

    operations = [
    ]
