# Generated by Django 4.1.3 on 2023-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0209_alerttrigger_alerttrigger_alert_trigger_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttrigger',
            name='change_percent',
            field=models.IntegerField(default=0),
        ),
    ]
