# Generated by Django 4.1.3 on 2023-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0209_merge_20230820_1416'),
        ('ledger', '0212_historicaltransfer_accepted_by_transfer_accepted_by'),
    ]

    operations = [
    ]
