# Generated by Django 4.1.3 on 2023-09-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0213_merge_20230829_1114'),
        ('ledger', '0214_networkasset_last_provider_update'),
    ]

    operations = [
    ]
