# Generated by Django 4.1.3 on 2023-09-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0215_merge_20230902_1330'),
        ('ledger', '0216_merge_20230903_1154'),
    ]

    operations = [
    ]
