# Generated by Django 4.1.3 on 2023-09-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0215_bulkassetalert_alerttrigger_chanel_and_more'),
        ('ledger', '0216_remove_network_kucoin_name'),
    ]

    operations = [
    ]
