# Generated by Django 4.1.3 on 2023-09-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0216_merge_20230911_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresskey',
            name='memo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
