# Generated by Django 4.1.3 on 2023-09-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0217_auto_20230918_1559'),
        ('ledger', '0217_coincategory_header'),
    ]

    operations = [
    ]
