# Generated by Django 4.1.3 on 2023-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0217_addresskey_memo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresskey',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='depositaddress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='addresskey',
            name='memo',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='addresskey',
            constraint=models.UniqueConstraint(condition=models.Q(('architecture__in', ['BNB']), _negated=True), fields=('account', 'address'), name='none_memo_unique_account_address'),
        ),
        migrations.AddConstraint(
            model_name='addresskey',
            constraint=models.UniqueConstraint(condition=models.Q(('architecture__in', ['BNB'])), fields=('account', 'address', 'memo'), name='none_memo_unique_account_address_memo'),
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('network__in', ['BNB']), _negated=True), fields=('network', 'address'), name='ledger_depositaddress_unique_network_address'),
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('network__in', ['BNB'])), fields=('network', 'address_key'), name='ledger_depositaddress_unique_network_addresskey'),
        ),
    ]
