# Generated by Django 4.1.3 on 2023-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0220_alter_addresskey_memo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marginposition',
            index=models.Index(fields=['side', 'status', 'symbol', 'liquidation_price'], name='position_idx'),
        ),
    ]
