# Generated by Django 4.1.3 on 2023-10-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0221_marginposition_position_idx'),
        ('ledger', '0221_networkasset_expected_hw_balance'),
    ]

    operations = [
    ]
