# Generated by Django 4.1.3 on 2023-10-23 08:33

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def populate_wallets(apps, sch):
    MarginPosition = apps.get_model('ledger', 'MarginPosition')
    MarginPosition.objects.all().update(asset_wallet=F('wallet'), base_wallet=F('wallet'))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0223_alter_marginposition_status_alter_trx_scope'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marginposition',
            name='position_idx',
        ),
        migrations.RemoveField(
            model_name='marginposition',
            name='side',
        ),
        migrations.AddField(
            model_name='marginposition',
            name='asset_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_wallet', to='ledger.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginposition',
            name='base_wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_wallet', to='ledger.wallet'),
            preserve_default=False,
        ),
        migrations.RunPython(code=populate_wallets, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='marginposition',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='marginposition',
            name='asset_wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_wallet', to='ledger.wallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marginposition',
            name='base_wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='base_wallet', to='ledger.wallet'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='marginposition',
            index=models.Index(fields=['status', 'symbol', 'liquidation_price'], name='position_idx'),
        ),
    ]
