# Generated by Django 4.1.3 on 2023-11-02 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0224_remove_marginposition_position_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='valid_balance_constraint',
        ),
        migrations.AddField(
            model_name='marginposition',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='marginposition',
            name='side',
            field=models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='marginposition',
            name='asset_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_wallet', to='ledger.wallet'),
        ),
        migrations.AlterField(
            model_name='marginposition',
            name='base_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_wallet', to='ledger.wallet'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('check_balance', False), models.Q(models.Q(('market__in', ('loan', 'debt', 'margin')), _negated=True), ('balance__gte', django.db.models.expressions.CombinedExpression(models.F('locked'), '-', models.F('credit')))), models.Q(('market__in', ('loan', 'debt')), ('balance__lte', 0), ('locked', 0)), models.Q(('market', 'margin'), ('variant__isnull', True), ('balance__gte', django.db.models.expressions.CombinedExpression(models.F('locked'), '-', models.F('credit')))), models.Q(('market', 'margin'), ('variant__isnull', False)), _connector='OR'), name='valid_balance_constraint'),
        ),
    ]
