# Generated by Django 4.1.3 on 2023-11-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0224_depositrecoveryrequest'),
        ('ledger', '0225_remove_wallet_valid_balance_constraint_and_more'),
    ]

    operations = [
    ]
