# Generated by Django 4.1.3 on 2023-11-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0226_merge_20231102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='variant',
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
