# Generated by Django 4.1.3 on 2023-11-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0227_alter_wallet_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='margin_enable',
        ),
    ]
