# Generated by Django 4.1.3 on 2023-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0228_remove_asset_margin_enable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trx',
            index=models.Index(fields=['scope', 'sender', 'created'], name='trx_margin_idx'),
        ),
    ]
