# Generated by Django 4.1.3 on 2023-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0226_alter_trx_scope_tokenrebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
