# Generated by Django 4.1.3 on 2023-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0228_remove_asset_margin_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='slow_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
