# Generated by Django 4.1.3 on 2023-11-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0229_network_slow_withdraw'),
        ('ledger', '0229_trx_trx_margin_idx'),
    ]

    operations = [
    ]
