# Generated by Django 4.1.3 on 2023-11-16 07:21

from django.db import migrations, models

from ledger.utils.external_price import SHORT


def populate_position(app, sch):
    MarginPosition = app.get_model('ledger.MarginPosition')
    MarginPosition.objects.filter(side__isnull=True).update(side=SHORT)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0229_trx_trx_margin_idx'),
    ]

    operations = [
        migrations.RunPython(populate_position, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='marginposition',
            name='side',
            field=models.CharField(choices=[('long', 'long'), ('short', 'short')], max_length=8),
            preserve_default=False,
        ),
    ]
