# Generated by Django 4.1.3 on 2023-11-23 14:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0166_auto_20231102_0952'),
        ('ledger', '0230_alter_marginposition_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginLeverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leverage', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30, validators=[django.core.validators.MinValueValidator(2)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
