# Generated by Django 4.1.3 on 2023-11-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0230_merge_20231113_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrecoveryrequest',
            name='sender_address',
        ),
    ]
