# Generated by Django 4.1.3 on 2023-12-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0231_marginhistorymodel_marginleverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginloan',
            name='account',
        ),
        migrations.RemoveField(
            model_name='marginloan',
            name='asset',
        ),
        migrations.RenameField(
            model_name='marginposition',
            old_name='net_amount',
            new_name='equity',
        ),
        migrations.DeleteModel(
            name='CloseRequest',
        ),
        migrations.DeleteModel(
            name='MarginLoan',
        ),
    ]
