# Generated by Django 4.1.3 on 2023-11-30 13:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0231_marginleverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginleverage',
            name='leverage',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
