# Generated by Django 4.1.3 on 2023-11-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0231_marginleverage'),
        ('ledger', '0231_remove_depositrecoveryrequest_sender_address'),
    ]

    operations = [
    ]
