# Generated by Django 4.1.3 on 2023-12-02 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0232_alter_marginleverage_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginposition',
            name='net_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
