# Generated by Django 4.1.3 on 2023-11-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0232_alter_marginleverage_leverage'),
        ('ledger', '0232_merge_20231125_1142'),
    ]

    operations = [
    ]
