# Generated by Django 4.1.3 on 2023-12-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0174_systemconfig_insurance_fee_percentage_and_more'),
        ('ledger', '0232_remove_marginloan_account_remove_marginloan_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginhistorymodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
