# Generated by Django 4.1.3 on 2023-12-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0233_marginposition_net_amount'),
        ('ledger', '0233_merge_20231130_1655'),
    ]

    operations = [
    ]
