# Generated by Django 4.1.3 on 2023-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0233_marginposition_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginposition',
            name='alert_mode',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
