# Generated by Django 4.1.3 on 2023-12-07 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0234_marginposition_alert_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginInterestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('group_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('debt', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition')),
            ],
            options={
                'unique_together': {('position', 'group_id', 'created')},
            },
        ),
    ]
