# Generated by Django 4.1.3 on 2023-12-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0234_marginposition_alert_mode'),
        ('ledger', '0234_merge_20231204_1204'),
    ]

    operations = [
    ]
