# Generated by Django 4.1.3 on 2023-12-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0235_margininteresthistory'),
        ('ledger', '0235_merge_20231204_1655'),
    ]

    operations = [
    ]
