# Generated by Django 4.1.3 on 2023-12-11 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0237_asset_margin_interest_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('pnl', 'pnl'), ('transfer', 'transfer'), ('trade_fee', 'trade_fee'), ('int_fee', 'int_fee'), ('ins_fee', 'ins_fee')], max_length=12)),
                ('group_id', models.UUIDField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition')),
            ],
        ),
        migrations.DeleteModel(
            name='MarginInterestHistory',
        ),
        migrations.AddConstraint(
            model_name='marginhistorymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'int_fee')), fields=('position', 'group_id', 'created'), name='position_group_id_created_unique'),
        ),
    ]
