# Generated by Django 4.1.3 on 2023-12-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0238_marginhistorymodel_delete_margininteresthistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginhistorymodel',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
        migrations.AlterField(
            model_name='marginhistorymodel',
            name='type',
            field=models.CharField(choices=[('pnl', 'pnl'), ('transfer', 'transfer'), ('trade_fee', 'trade_fee'), ('int_fee', 'int_fee'), ('ins_fee', 'ins_fee'), ('p_transfer', 'p_transfer')], max_length=12),
        ),
    ]
