# Generated by Django 4.1.3 on 2023-12-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0230_alter_addressbook_account'),
        ('ledger', '0239_alter_marginhistorymodel_position_and_more'),
    ]

    operations = [
    ]
