# Generated by Django 4.1.3 on 2023-09-23 07:54

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_historicalcoinpricecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_en', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.baseitem')),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.section')),
            ],
            bases=('multimedia.baseitem',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.baseitem')),
                ('uuid', models.UUIDField(default=uuid.UUID('9a101d17-396a-4015-a540-beb1842af0c3'), editable=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('content', django_quill.fields.QuillField()),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.section')),
            ],
            bases=('multimedia.baseitem',),
        ),
    ]
