# Generated by Django 4.1.3 on 2023-09-18 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_historicalcoinpricecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_en', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('d80b536b-343d-42e9-88cf-521f70ea5f33'), editable=False)),
                ('slug', models.SlugField(max_length=255)),
                ('parent_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.section')),
            ],
        ),
    ]
