# Generated by Django 4.1.3 on 2023-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0023_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=104857600, upload_to=''),
        ),
    ]
