# Generated by Django 4.0 on 2022-03-16 12:57

from django.db import migrations

from ledger.models import OTCTrade
from market.models import FillOrder


def populate_fill_orders(apps, schema_editor):
    for trade in OTCTrade.objects.filter(status='done'):
        FillOrder.create_for_otc_trade(trade)


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0005_fillorder_base_amount_fillorder_maker_fee_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(code=populate_fill_orders, reverse_code=migrations.RunPython.noop),
    ]
