# Generated by Django 4.0 on 2022-03-13 09:23

from decimal import Decimal

from django.db import migrations

from ledger.utils.precision import floor_precision
from ledger.utils.price import get_trading_price_usdt, BUY
from ledger.utils.price_manager import PriceManager


def set_maker_quantities(apps, schema_editor):
    PairSymbol = apps.get_model('market', 'PairSymbol')
    with PriceManager(fetch_all=True):
        for symbol in PairSymbol.objects.all():
            symbol.maker_amount = floor_precision(
                (Decimal(400) / get_trading_price_usdt(symbol.asset.symbol, BUY, raw_price=True)), symbol.step_size)
            symbol.save()


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0007_fillorder_market_fill_created_ce1544_idx'),
    ]

    operations = [
        migrations.RunPython(
            code=set_maker_quantities, reverse_code=migrations.RunPython.noop
        ),
    ]
