# Generated by Django 4.0 on 2022-05-15 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_stoploss_order_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsymbol',
            name='taker_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.002'), max_digits=9),
        ),
    ]
