# Generated by Django 4.0 on 2022-06-20 07:08

from django.db import migrations, models
import uuid


def populate_order_group_id(apps, schema_editor):
    Order = apps.get_model('market', 'Order')

    orders = list(Order.objects.all())
    for order in orders:
        order.group_id = uuid.uuid4()

    Order.objects.bulk_update(orders, ['group_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_fillorder_amount_alter_fillorder_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.UUIDField(null=True),
        ),

        migrations.RunPython(
            code=populate_order_group_id, reverse_code=migrations.RunPython.noop
        ),

        migrations.AlterField(
            model_name='order',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
