# Generated by Django 4.1.3 on 2023-02-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_pairsymbol_last_trade_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(blank=True, choices=[(None, 'GTC'), ('FOK', 'FOK')], max_length=4, null=True),
        ),
    ]
