# Generated by Django 4.1.3 on 2023-02-08 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_remove_trade_gap_revenue_remove_trade_hedge_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fee_revenue',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
