# Generated by Django 4.1.3 on 2023-03-01 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_alter_order_group_id_alter_trade_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='base_usdt_price',
            field=models.DecimalField(decimal_places=20, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
