# Generated by Django 4.1.3 on 2023-05-28 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='group_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
