# Generated by Django 4.1.3 on 2023-06-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_order_market_order_unique_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairsymbol',
            name='maker_amount',
        ),
        migrations.RemoveField(
            model_name='pairsymbol',
            name='market_maker_enabled',
        ),
    ]
