# Generated by Django 4.1.3 on 2023-05-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_alter_order_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stop_loss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.stoploss'),
        ),
    ]
