# Generated by Django 4.1.3 on 2023-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_remove_pairsymbol_maker_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pairsymbol',
            name='check_market_pairsymbol_amounts',
        ),
        migrations.AddConstraint(
            model_name='pairsymbol',
            constraint=models.CheckConstraint(check=models.Q(('max_trade_quantity__gte', 0), ('min_trade_quantity__gte', 0)), name='check_market_pairsymbol_amounts'),
        ),
    ]
