# Generated by Django 4.1.3 on 2023-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('depth', 'depth'), ('bot', 'bot'), (None, 'ordinary'), ('liquid', 'liquid')], max_length=8, null=True),
        ),
    ]
