# Generated by Django 4.1.3 on 2023-11-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_alter_order_type'),
        ('market', '0057_remove_pairsymbol_maker_fee_and_more'),
    ]

    operations = [
    ]
