# Generated by Django 4.1.3 on 2023-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0058_merge_20231102_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsymbol',
            name='margin_enable',
            field=models.BooleanField(default=False),
        ),
    ]
