# Generated by Django 4.1.3 on 2023-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_pairsymbol_margin_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_open_position',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
