# Generated by Django 4.1.3 on 2023-12-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0234_marginposition_alert_mode'),
        ('market', '0060_order_is_open_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.marginposition'),
        ),
    ]
