# Generated by Django 4.0 on 2022-03-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_paydotirgateway_alter_gateway_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('-verified',), 'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب\u200cهای بانکی'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'ordering': ('-verified',), 'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'کارت\u200cهای بانکی'},
        ),
    ]
