# Generated by Django 4.0 on 2022-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_remove_fiatwithdrawrequest_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='fee_amount',
            field=models.PositiveIntegerField(default=5000, verbose_name='کارمزد'),
        ),
    ]
