# Generated by Django 4.0 on 2022-08-02 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0112_alter_wallet_unique_together'),
        ('financial', '0043_alter_marketingcost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('done', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.asset')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=256)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.investment')),
            ],
        ),
    ]
