# Generated by Django 4.0 on 2022-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0063_alter_paymentrequest_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrevenue',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='finance/'),
        ),
    ]
