# Generated by Django 4.1.3 on 2023-02-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0071_historicalfiatwithdrawrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiatHedgeTrx',
        ),
    ]
