# Generated by Django 4.1.3 on 2023-04-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0077_bankpaymentid_paymentidrequest'),
        ('financial', '0078_rename_api_key_gateway_withdraw_api_key_and_more'),
    ]

    operations = [
    ]
