# Generated by Django 4.1.3 on 2023-07-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0094_merge_20230711_1138'),
        ('financial', '0097_payment_description'),
    ]

    operations = [
    ]
