# Generated by Django 4.1.3 on 2023-07-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0092_fiatwithdrawrequest_login_activity_and_more'),
        ('financial', '0099_alter_bankpaymentrequest_ref_id_alter_payment_ref_id'),
    ]

    operations = [
    ]
