# Generated by Django 4.1.3 on 2023-08-02 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0101_gateway_withdraw_api_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='batch_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manualtransfer',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='manualtransfer',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='میزان برداشت'),
        ),
        migrations.AlterField(
            model_name='manualtransfer',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.gateway'),
        ),
    ]
