# Generated by Django 4.1.3 on 2023-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0102_gateway_batch_id_manualtransfer_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransfer',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AlterField(
            model_name='fiatwithdrawrequest',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AlterField(
            model_name='historicalfiatwithdrawrequest',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
