# Generated by Django 4.0 on 2021-12-28 10:08

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', error_messages={'unique': 'شماره موبایل وارد شده از قبل در سیستم موجود است.'}, max_length=16, unique=True, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
