# Generated by Django 4.0 on 2022-01-01 08:52

import accounts.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.CustomUserManager()),
            ],
        ),
    ]
