# Generated by Django 4.0 on 2021-12-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_alter_wallet_account'),
        ('accounts', '0003_remove_account_user_user_email_verification_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
