# Generated by Django 4.0 on 2021-12-28 15:46

import accounts.utils
import accounts.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=accounts.utils.fifteen_minutes_later_datetime)),
                ('phone_number', models.CharField(db_index=True, max_length=16, validators=[accounts.validators.mobile_number_validator], verbose_name='شماره تماس')),
                ('code', models.CharField(db_index=True, default=accounts.utils.generate_random_code, max_length=6)),
                ('used', models.BooleanField(default=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
