# Generated by Django 4.0 on 2021-12-29 08:09

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='scope',
            field=models.CharField(choices=[('forget', 'forget'), ('verify', 'verify')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(db_index=True, default=accounts.utils.generate_random_code, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
