# Generated by Django 4.0 on 2022-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_finotechrequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='first_trade_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='level_2_prize_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='sign_up_prize_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ایجاد حساب کاربری'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_trade_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_2_prize_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_prize_activate_mood',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ایجاد حساب کاربری'),
        ),
    ]
