# Generated by Django 4.0 on 2022-03-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_historicaluser_first_trade_activate_mood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='level_2_prize_activate_mood',
            new_name='level_2_prize_activate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='level_2_prize_activate_mood',
            new_name='level_2_prize_activate',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='first_trade_activate_mood',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='sign_up_prize_activate_mood',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_trade_activate_mood',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sign_up_prize_activate_mood',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=True, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=True, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
    ]
