# Generated by Django 4.0 on 2022-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_historicaluser_archived_user_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='level_2_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_2_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
    ]
