# Generated by Django 4.0 on 2022-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_level_2_prize_activate_mood_historicaluser_level_2_prize_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='level_2_prize_activate',
            field=models.BooleanField(default=True, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_2_prize_activate',
            field=models.BooleanField(default=True, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
    ]
