# Generated by Django 4.0 on 2022-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_historicaluser_level_2_prize_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level_2_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_trade_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه اولین معامله'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_2_prize_activate',
            field=models.BooleanField(default=False, verbose_name='امکان دریافت جایزه ارتقا به سطح ۲'),
        ),
    ]
