# Generated by Django 4.0 on 2022-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_sentsms_externalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='after_sign_up_status',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='after_sign_up_status',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], max_length=10, null=True),
        ),
    ]
