# Generated by Django 4.0 on 2022-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_historicaluser_after_sign_up_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='after_sign_up_status',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='after_sign_up_status',
            field=models.CharField(blank=True, choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='', max_length=10),
        ),
    ]
