# Generated by Django 4.0 on 2022-04-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_historicaluser_after_sign_up_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='after_sign_up_status',
            new_name='on_boarding_flow',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='after_sign_up_status',
            new_name='on_boarding_flow',
        ),
    ]
