# Generated by Django 4.0 on 2022-05-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_merge_20220427_1454'),
        ('accounts', '0039_merge_20220420_1937'),
    ]

    operations = [
    ]
