# Generated by Django 4.0 on 2022-05-08 06:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_merge_20220508_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('ip_list', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(default='{127.0.0.1}'), default=[], size=None)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='selfie_image_verifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.user', verbose_name='تایید کننده عکس سلفی'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='withdraw_before_48h_option',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت وجه پیش از سپری شدن ۴۸ ساعت از اولین واریز'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='تایید کننده عکس سلفی'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_before_48h_option',
            field=models.BooleanField(default=False, verbose_name='امکان برداشت وجه پیش از سپری شدن ۴۸ ساعت از اولین واریز'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level_2_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح ۲'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level_3_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح 3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_2_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح ۲'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_3_verify_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سطح 3'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('level__gt', 1)), fields=('national_code',), name='unique_verified_national_code'),
        ),
        migrations.AddField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='accounts.user', verbose_name='User'),
        ),
    ]
