# Generated by Django 4.0 on 2022-05-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_historicaluser_withdraw_before_48_h_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='withdraw_before_48_h_option',
            new_name='withdraw_before_48h_option',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='withdraw_before_48_h_option',
            new_name='withdraw_before_48h_option',
        ),
    ]
