# Generated by Django 4.0 on 2022-05-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_customtoken'),
        ('accounts', '0043_merge_20220501_1306'),
    ]

    operations = [
    ]
