# Generated by Django 4.0 on 2022-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_account_trade_volume_irt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='selfie_image_uploaded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آپلود عکس سلفی'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image_uploaded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آپلود عکس سلفی'),
        ),
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize'), ('trade_prize', 'trade_prize')], max_length=22),
        ),
    ]
