# Generated by Django 4.0 on 2022-05-10 14:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_historicaluser_selfie_image_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='trade_volume_irt',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='selfie_image_uploaded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selfie_image_uploaded',
        ),
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize')], max_length=22),
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('ip_list', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(default='{127.0.0.1}'), default=[], size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
    ]
