# Generated by Django 4.0 on 2022-05-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_loginactivity'),
        ('accounts', '0046_historicaluser_selfie_image_uploaded_and_more'),
    ]

    operations = [
    ]
