# Generated by Django 4.0 on 2022-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_account_trade_volume_irt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trade_volume_irt',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='externalnotification',
            name='scope',
            field=models.CharField(choices=[('level_2_prize', 'level_2_prize'), ('first_deposit_prize', 'first_deposit_prize'), ('trade_prize', 'trade_prize')], max_length=22),
        ),
    ]
