# Generated by Django 4.0 on 2022-05-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_account_trade_volume_irt_and_more'),
        ('accounts', '0048_alter_externalnotification_scope'),
    ]

    operations = [
    ]
