# Generated by Django 4.0 on 2022-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0082_alter_networkasset_withdraw_fee_and_more'),
        ('market', '0018_alter_pairsymbol_taker_fee'),
        ('accounts', '0051_alter_verificationcode_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bookmark_assets',
            field=models.ManyToManyField(blank=True, null=True, to='ledger.Asset'),
        ),
        migrations.AddField(
            model_name='account',
            name='bookmark_market',
            field=models.ManyToManyField(blank=True, null=True, to='market.PairSymbol'),
        ),
    ]
