# Generated by Django 4.0 on 2022-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0082_alter_networkasset_withdraw_fee_and_more'),
        ('accounts', '0052_account_bookmark_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bookmark_asset',
            field=models.ManyToManyField(blank=True, null=True, to='ledger.Asset'),
        ),
    ]
