# Generated by Django 4.0 on 2022-07-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0063_alter_externalnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='customtoken',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
