# Generated by Django 4.0 on 2022-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_externalnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('s', 'system'), ('o', 'out'), (None, 'ordinary'), ('st', 'stake')], max_length=2, null=True),
        ),
    ]
