# Generated by Django 4.0 on 2022-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('s', 'system'), ('o', 'out'), (None, 'ordinary')], max_length=1, null=True),
        ),
    ]
