# Generated by Django 4.0 on 2022-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_merge_20220712_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetoken',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='firebasetoken',
            name='state',
            field=models.CharField(choices=[('1', 'token_between_2h_1d'), ('2', 'Token_between_1d_7d'), ('3', 'token_more_than_7d')], default='1', max_length=1),
        ),
    ]
