# Generated by Django 4.0 on 2022-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_firebasetoken_created_firebasetoken_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
