# Generated by Django 4.0 on 2022-08-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_alter_finotechrequest_user'),
        ('accounts', '0078_historicaluser_reject_reason_user_reject_reason_and_more'),
    ]

    operations = [
    ]
