# Generated by Django 4.0 on 2022-09-21 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_loginactivity_ip_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth2Fa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qrcode', models.ImageField(upload_to='qrcode')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth2fa', to='accounts.user')),
            ],
            options={
                'verbose_name': 'رمز دوعاملی',
                'verbose_name_plural': 'رمز دوعاملی',
            },
        ),
    ]
