# Generated by Django 4.0 on 2022-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_alter_verificationcode_scope_auth2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='promotion',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
