# Generated by Django 4.0 on 2022-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_trafficsource_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsource',
            name='promotion',
            field=models.CharField(blank=True, choices=[('shib', 'shib'), ('voucher', 'voucher')], max_length=256),
        ),
    ]
