# Generated by Django 4.0 on 2022-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_trafficsource_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsource',
            name='promotion',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='promotion',
            field=models.CharField(blank=True, choices=[('shib', 'shib'), ('voucher', 'voucher')], max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='promotion',
            field=models.CharField(blank=True, choices=[('shib', 'shib'), ('voucher', 'voucher')], max_length=256),
        ),
    ]
