# Generated by Django 4.0 on 2022-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_historicaluser_promotion_alter_user_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='show_community',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده کامیونیتی'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_community',
            field=models.BooleanField(default=False, verbose_name='امکان مشاهده کامیونیتی'),
        ),
    ]
