# Generated by Django 4.0 on 2022-11-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_merge_20221120_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='allow_level1_crypto_withdraw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_level1_crypto_withdraw',
        ),
    ]
