# Generated by Django 4.1.3 on 2023-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_account_owned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsource',
            options={'permissions': [('read_yektanet_mobile', 'Can read yektanet mobile analytics'), ('read_mediaad', 'Can read mediaad analytics')], 'verbose_name': 'منشا ترافیک', 'verbose_name_plural': 'منشا ترافیک'},
        ),
    ]
