# Generated by Django 4.1.3 on 2023-06-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_alter_bulknotification_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsource',
            options={'verbose_name': 'منشا ترافیک', 'verbose_name_plural': 'منشا ترافیک'},
        ),
    ]
