# Generated by Django 4.0 on 2023-07-24 11:11

from django.db import migrations, models
import django.db.models.deletion


def generate_template(apps, sch):
    Template = apps.get_model('accounts', 'Template')
    Template.objects.create(target='system', content='{last}')
    Template.objects.create(target='like', content='{last} و {count} نفر دیگر پست شما را پسندیدند')
    Template.objects.create(target='comment', content='{last} و {count} نفر دیگر برای پست شما نظر گزاشتند')
    Template.objects.create(target='follow', content='{last} و {count} نفر دیگر شما را دنبال کردند')


def populate_template(apps, sch):
    Template = apps.get_model('accounts', 'Template')
    Notification = apps.get_model('accounts', 'Notification')

    template = Template.objects.get(target='system')
    Notification.objects.all().update(template=template)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_merge_20230711_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(null=True)),
                ('target', models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('system', 'system')], default='system', max_length=8)),
            ],
        ),
        migrations.RunPython(generate_template, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('raastin', 'raastin'), ('ninja', 'ninja')], default='raastin', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('system', 'system')], default='system', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ord', 'ord'), ('rep', 'rep'), ('dif', 'dif')], default='ord', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('read', False), ('source', 'ninja')), fields=('group_id', 'target'), name='unique_unread_group_id'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.template'),
        ),
        migrations.RunPython(populate_template, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.template'),
        ),
    ]
