# Generated by Django 4.1.3 on 2023-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_merge_20230711_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='scope',
            field=models.CharField(choices=[('forget', 'forget'), ('verify', 'verify'), ('withdraw', 'withdraw'), ('tel', 'tel'), ('change_pass', 'change_pass'), ('change_phone', 'change_phone'), ('email_verify', 'email_verify'), ('fiat_withdraw', 'fiat_withdraw'), ('2fa_activate', '2fa_activate'), ('2fa_deactivate', '2fa_deactivate')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Auth2Fa',
        ),
    ]
