# Generated by Django 4.1.3 on 2023-07-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_merge_20230711_1255'),
        ('accounts', '0138_merge_20230711_1521'),
    ]

    operations = [
    ]
