# Generated by Django 4.1.3 on 2023-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_template_notification_count_notification_source_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'system')), fields=('recipient', 'group_id'), name='unique_recipient_group_id'),
        ),
    ]
