# Generated by Django 4.1.3 on 2023-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_alter_verificationcode_scope_delete_auth2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='scope',
            field=models.CharField(choices=[('forget', 'forget'), ('verify', 'verify'), ('withdraw', 'withdraw'), ('tel', 'tel'), ('change_pass', 'change_pass'), ('change_phone', 'change_phone'), ('email_verify', 'email_verify'), ('fiat_withdraw', 'fiat_withdraw'), ('2fa', '2fa')], max_length=32),
        ),
    ]
