# Generated by Django 4.1.3 on 2023-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_unread_group_id',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_recipient_group_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='template'
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='target',
            new_name='template',
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('plain', 'plain')], default='plain', max_length=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('core', 'core'), ('ninja', 'ninja'), ('crm', 'crm')], default='core', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('read', False), ('source', 'ninja')), fields=('group_id', 'template'), name='unique_unread_group_id'),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('template', 'plain')),
                                               fields=('recipient', 'group_id'), name='unique_recipient_group_id'),
        ),
    ]
