# Generated by Django 4.1.3 on 2023-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_historicaluser_suspended_until_user_suspended_until_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginactivity',
            name='login_suspension_idx',
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'device'], name='login_suspension_idx'),
        ),
    ]
