# Generated by Django 4.1.3 on 2023-08-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_merge_20230802_1738'),
        ('accounts', '0141_merge_20230822_1235'),
    ]

    operations = [
    ]
