# Generated by Django 4.1.3 on 2023-08-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_remove_historicaluser_withdraw_before_48h_option_and_more'),
        ('accounts', '0141_merge_20230802_1738'),
    ]

    operations = [
    ]
