# Generated by Django 4.1.3 on 2023-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_merge_20230822_1235'),
        ('accounts', '0142_merge_20230820_1416'),
    ]

    operations = [
    ]
