# Generated by Django 4.1.3 on 2023-09-05 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_merge_20230829_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('withdraw', 'withdraw'), ('trade', 'trade')], max_length=10), blank=True, default=['trade'], null=True, size=None),
        ),
    ]
