# Generated by Django 4.1.3 on 2023-09-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_historicaluser_suspended_until_user_suspended_until_and_more'),
        ('accounts', '0141_merge_20230802_1738'),
        ('accounts', '0143_alter_customtoken_scopes'),
    ]

    operations = [
    ]
