# Generated by Django 4.1.3 on 2023-09-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0143_alter_customtoken_scopes'),
        ('accounts', '0143_merge_20230829_1114'),
    ]

    operations = [
    ]
