# Generated by Django 4.1.3 on 2023-09-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_historicaluser_suspended_until_user_suspended_until_and_more'),
        ('accounts', '0142_historicaluser_is_price_notif_on_and_more'),
        ('accounts', '0143_alter_customtoken_scopes'),
    ]

    operations = [
    ]
