# Generated by Django 4.1.3 on 2023-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_historicaluser_is_price_notif_on_and_more'),
        ('accounts', '0144_merge_20230905_1648'),
    ]

    operations = [
    ]
