# Generated by Django 4.1.3 on 2023-09-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_merge_20230910_1531'),
        ('accounts', '0144_merge_20230910_1553'),
    ]

    operations = [
    ]
