# Generated by Django 4.1.3 on 2023-09-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0146_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_consulted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_consulted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('DONE', 'DONE')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('consultee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultee_consultations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متقاضی مشاوره')),
                ('consulter', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consulter_consultations', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'درخواستهای مشاوره',
            },
        ),
    ]
