# Generated by Django 4.1.3 on 2023-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_rename_consultation_consultee_consultation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
