# Generated by Django 4.1.3 on 2023-10-25 15:00

import accounts.models.company
import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0021_file'),
        ('accounts', '0158_account_custom_maker_fee_account_custom_taker_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('company_registration_date', models.CharField(blank=True, max_length=128, null=True)),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[accounts.validators.company_national_id_validator])),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('fetched_data', models.JSONField(blank=True, null=True)),
                ('docs_state', models.CharField(choices=[('INITIALIZED', 'initial'), ('PENDING', 'pending'), ('INFORMATION_NO_FETCHED', 'company_information_not_fetched'), ('REJECTED', 'rejected'), ('VERIFIED', 'verified')], default=accounts.models.company.State['INITIALIZED'], max_length=128)),
                ('information_state', models.CharField(choices=[('INITIALIZED', 'initial'), ('PENDING', 'pending'), ('INFORMATION_NO_FETCHED', 'company_information_not_fetched'), ('REJECTED', 'rejected'), ('VERIFIED', 'verified')], default=accounts.models.company.State['INITIALIZED'], max_length=128)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('company_documents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='multimedia.file', verbose_name='مدارک شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.company'),
        ),
    ]
