# Generated by Django 4.1.3 on 2023-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0159_company_historicaluser_company_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelGrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_daily_crypto_withdraw', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('max_daily_fiat_withdraw', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('max_daily_fiat_deposit', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='custom_fiat_withdraw_ceil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_fiat_withdraw_ceil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='سطح'),
        ),
    ]
