# Generated by Django 4.1.3 on 2023-11-02 06:22

from django.db import migrations


def populate_level_grants(apps, schema_editor):
    LevelGrants = apps.get_model('accounts', 'LevelGrants')

    LevelGrants.objects.create(
        level=1,
        max_daily_crypto_withdraw=0,
        max_daily_fiat_withdraw=0,
        max_daily_fiat_deposit=0
    )

    LevelGrants.objects.create(
        level=2,
        max_daily_crypto_withdraw=200_000_000,
        max_daily_fiat_withdraw=200_000_000,
    )

    LevelGrants.objects.create(
        level=3,
        max_daily_crypto_withdraw=200_000_000,
        max_daily_fiat_withdraw=200_000_000,
    )

    LevelGrants.objects.create(
        level=4,
        max_daily_crypto_withdraw=200_000_000,
        max_daily_fiat_withdraw=200_000_000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0163_alter_company_registration_id'),
    ]

    operations = [
        migrations.RunPython(code=populate_level_grants, reverse_code=migrations.RunPython.noop)
    ]
