# Generated by Django 4.1.3 on 2023-12-11 08:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0167_alter_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='max_margin_leverage',
            field=models.DecimalField(decimal_places=8, default=Decimal('5'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_margin_irt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_margin_usdt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_user_margin_irt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('500000000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='total_user_margin_usdt_base',
            field=models.DecimalField(decimal_places=8, default=Decimal('10000'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
