# Generated by Django 4.1.3 on 2023-12-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0168_systemconfig_max_margin_leverage_and_more'),
        ('accounts', '0172_alter_userfeatureperm_feature'),
    ]

    operations = [
    ]
