# Generated by Django 4.0 on 2022-01-19 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0010_remove_otctrade_provider_order_id_otctrade_lock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(default='binance', max_length=8)),
                ('market', models.CharField(default='fut', max_length=4)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('order_id', models.CharField(blank=True, max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
            ],
        ),
    ]
