# Generated by Django 4.0 on 2022-01-26 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
