# Generated by Django 4.0 on 2022-01-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_providerorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='scope',
            field=models.CharField(choices=[('t', 'trade'), ('b', 'borrow'), ('l', 'liquidation')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
