# Generated by Django 4.0 on 2022-02-06 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_network_address_regex_transfer_handling'),
        ('provider', '0003_providerorder_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='scope',
            field=models.CharField(choices=[('trade', 'trade'), ('borrow', 'borrow'), ('liquid', 'liquidation'), ('withdraw', 'withdraw')], max_length=8),
        ),
        migrations.CreateModel(
            name='ProviderTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(default='binance', max_length=8)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=256)),
                ('provider_transfer_id', models.CharField(max_length=64)),
                ('caller_id', models.CharField(blank=True, max_length=64)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.network')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderHedgedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('caller_id', models.PositiveIntegerField(blank=True, null=True)),
                ('hedged', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.asset')),
                ('spot_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='provider.providerorder')),
            ],
        ),
    ]
