# Generated by Django 4.0 on 2022-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_providerorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='market',
            field=models.CharField(choices=[('spot', 'spot'), ('fut', 'future'), ('mar', 'margin')], default='fut', max_length=4),
        ),
    ]
