# Generated by Django 4.0 on 2022-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_alter_providerhedgedorder_caller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='scope',
            field=models.CharField(choices=[('trade', 'trade'), ('borrow', 'borrow'), ('liquid', 'liquidation'), ('withdraw', 'withdraw'), ('hedge', 'hedge')], max_length=8),
        ),
    ]
