# Generated by Django 4.0 on 2022-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_alter_providerorder_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='وضعیت')),
                ('url', models.CharField(max_length=256)),
                ('data', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(max_length=8)),
                ('response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
