# Generated by Django 4.0 on 2022-06-13 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_binancerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerhedgedorder',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providerorder',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='providertransfer',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='providerhedgedorder',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_provider_hedged_order_amount'),
        ),
        migrations.AddConstraint(
            model_name='providerorder',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_provider_order_amount'),
        ),
        migrations.AddConstraint(
            model_name='providertransfer',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='check_provider_transfer_amount'),
        ),
    ]
