# Generated by Django 4.0 on 2022-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_alter_providerhedgedorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='exchange',
            field=models.CharField(max_length=8),
        ),
    ]
