# Generated by Django 4.0 on 2022-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_alter_providerhedgedorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertransfer',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
