# Generated by Django 4.0 on 2022-07-17 07:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_providertransfer_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='hedge_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
