# Generated by Django 4.0 on 2022-07-23 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_providertransfer_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceWithdrawDepositHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(max_length=16)),
                ('time', models.DateTimeField()),
                ('network', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], max_length=16)),
                ('type', models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit')], max_length=16)),
            ],
        ),
    ]
