# Generated by Django 4.0 on 2022-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_alter_providertransfer_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='exchange',
            field=models.CharField(max_length=32),
        ),
    ]
