# Generated by Django 4.0 on 2022-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_providerorder_hedge_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='scope',
            field=models.CharField(choices=[('trade', 'trade'), ('borrow', 'borrow'), ('liquid', 'liquidation'), ('withdraw', 'withdraw'), ('hedge', 'hedge'), ('prv-base', 'prv-base')], max_length=8),
        ),
    ]
