# Generated by Django 4.0 on 2022-07-26 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_providerorder_hedge_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('binance_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('coin', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('network', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('done', 'done')], max_length=16)),
                ('type', models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BinanceWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=16)),
                ('free', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('locked', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('spot', 'spot'), ('futures', 'futures')], max_length=16)),
            ],
            options={
                'unique_together': {('asset', 'type')},
            },
        ),
    ]
