# Generated by Django 4.0 on 2022-07-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_binancewithdrawdeposithistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binancewithdrawdeposithistory',
            old_name='time',
            new_name='date',
        ),
    ]
