# Generated by Django 4.0 on 2022-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_alter_providerorder_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='exchange',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='providertransfer',
            name='exchange',
            field=models.CharField(default='binance', max_length=16),
        ),
    ]
