# Generated by Django 4.0 on 2022-07-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_alter_providerorder_scope'),
        ('provider', '0013_binancetransferhistory_binancewallet'),
    ]

    operations = [
    ]
