# Generated by Django 4.0 on 2022-07-23 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_rename_time_binancewithdrawdeposithistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=16)),
                ('free', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('locked', models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
