# Generated by Django 4.0 on 2022-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_alter_providerorder_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertransfer',
            name='exchange',
            field=models.CharField(default='binance', max_length=16),
        ),
    ]
