# Generated by Django 4.0 on 2022-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_binancewallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='binancewallet',
            name='type',
            field=models.CharField(choices=[('spot', 'spot'), ('futures', 'futures')], default='spot', max_length=16),
            preserve_default=False,
        ),
    ]
