# Generated by Django 4.0 on 2022-08-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_alter_providerorder_exchange_and_more'),
        ('provider', '0015_binancewallet_usdt_value'),
    ]

    operations = [
    ]
