# Generated by Django 4.0 on 2022-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_merge_20220813_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerorder',
            name='scope',
            field=models.CharField(choices=[('trade', 'trade'), ('borrow', 'borrow'), ('liquid', 'liquidation'), ('withdraw', 'withdraw'), ('hedge', 'hedge'), ('prv-base', 'prv-base'), ('fake', 'fake')], max_length=8),
        ),
    ]
