# Generated by Django 4.0 on 2022-08-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_alter_providerorder_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinanceRequests',
            new_name='ProviderRequest',
        ),
        migrations.AddField(
            model_name='providerrequest',
            name='name',
            field=models.CharField(choices=[('binance', 'binance'), ('kucoin', 'kucoin'), ('mexc', 'mexc')],
                                   default='binance', max_length=16),
            preserve_default=False,
        ),
    ]
