# Generated by Django 4.0 on 2022-04-16 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0008_set_maker_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('below', models.BooleanField(default=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.pairsymbol')),
            ],
        ),
    ]
