# Generated by Django 4.0 on 2022-04-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovingAverage',
        ),
    ]
