# Generated by Django 4.0 on 2022-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarketcap',
            name='volume_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
