# Generated by Django 4.0 on 2022-03-15 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_coinmarketcap_volume_24h'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=64)),
                ('income_type', models.CharField(max_length=64)),
                ('tran_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('income', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.CharField(max_length=32)),
                ('income_date', models.DateTimeField()),
            ],
        ),
    ]
