# Generated by Django 4.0 on 2022-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_binanceincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarketcap',
            name='change_1h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='circulating_supply',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='cmc_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='high_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='low_24h',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
