# Generated by Django 4.0 on 2022-06-13 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_coinmarketcap_change_1h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceincome',
            name='income',
            field=models.DecimalField(decimal_places=8, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
