# Generated by Django 4.0 on 2022-01-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='key',
            new_name='encrypted_key',
        ),
    ]
