# Generated by Django 4.1.3 on 2023-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='scope',
            field=models.CharField(choices=[('v', 'verify'), ('d', 'deposit')], max_length=1),
        ),
    ]
