# Generated by Django 4.1.3 on 2023-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_alter_link_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='scope',
            field=models.CharField(choices=[('d', 'deposit')], max_length=1),
        ),
    ]
