# Generated by Django 4.0 on 2022-10-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0004_upgrade_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='scope',
        ),
    ]
