# Generated by Django 4.1.3 on 2023-07-30 09:17

from django.db import migrations, models

from gamify.models import MissionJourney


def populate_user_missions(apps, sch):
    UserMission = apps.get_model('gamify', 'UserMission')
    MissionTemplate = apps.get_model('gamify', 'MissionTemplate')
    User = apps.get_model('accounts', 'User')
    Account = apps.get_model('accounts', 'Account')

    user_mission_list = []

    for user in User.objects.all():
        account = Account.objects.filter(user=user).first()
        if not account:
            continue

        journey = MissionJourney.get_journey(account)

        for mission in MissionTemplate.objects.filter(journey=journey):
            try:
                UserMission.objects.filter(
                    user=user,
                    mission=mission,
                ).first()
            except UserMission.DoesNotExist:
                user_mission_list.append(
                    UserMission(
                        user=user,
                        mission=mission,
                        is_done=mission.finished(account)
                    )
                )
        UserMission.objects.bulk_create(user_mission_list)


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0017_alter_missionjourney_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_user_missions, migrations.RunPython.noop)
    ]
