# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade.proto',
  package='trade',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btrade.proto\x12\x05trade\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n\x0bTradeParams\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0f\n\x07symbols\x18\x02 \x03(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08order_by\x18\x06 \x03(\t\x12\x10\n\x08\x64istinct\x18\x07 \x03(\t\x12\x0e\n\x06values\x18\x08 \x03(\t\x12\r\n\x05limit\x18\t \x01(\x05\"a\n\x0fTradeTimeParams\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x15\n\rmin_timestamp\x18\x03 \x01(\x03\x12\x15\n\rmax_timestamp\x18\x04 \x01(\x03\"\x7f\n\tTradeList\x12&\n\x06trades\x18\x01 \x03(\x0b\x32\x16.trade.TradeList.Trade\x1aJ\n\x05Trade\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x02\x12\r\n\x05price\x18\x04 \x01(\x02\" \n\x0f\x41ggregatedValue\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x99\x02\n\x05Trade\x12:\n\x10GetCurrentTrades\x12\x12.trade.TradeParams\x1a\x10.trade.TradeList\"\x00\x12\x41\n\x11GetTradesAvgPrice\x12\x12.trade.TradeParams\x1a\x16.trade.AggregatedValue\"\x00\x12K\n\x17GetTradesAvgPriceByTime\x12\x16.trade.TradeTimeParams\x1a\x16.trade.AggregatedValue\"\x00\x12\x44\n\x14GetTradesSumQuantity\x12\x12.trade.TradeParams\x1a\x16.trade.AggregatedValue\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TRADEPARAMS = _descriptor.Descriptor(
  name='TradeParams',
  full_name='trade.TradeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='trade.TradeParams.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbols', full_name='trade.TradeParams.symbols', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='trade.TradeParams.timestamp', index=2,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_by', full_name='trade.TradeParams.order_by', index=3,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distinct', full_name='trade.TradeParams.distinct', index=4,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='trade.TradeParams.values', index=5,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='trade.TradeParams.limit', index=6,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=186,
)


_TRADETIMEPARAMS = _descriptor.Descriptor(
  name='TradeTimeParams',
  full_name='trade.TradeTimeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='trade.TradeTimeParams.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='trade.TradeTimeParams.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_timestamp', full_name='trade.TradeTimeParams.min_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_timestamp', full_name='trade.TradeTimeParams.max_timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=285,
)


_TRADELIST_TRADE = _descriptor.Descriptor(
  name='Trade',
  full_name='trade.TradeList.Trade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='trade.TradeList.Trade.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='trade.TradeList.Trade.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='trade.TradeList.Trade.quantity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='trade.TradeList.Trade.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=414,
)

_TRADELIST = _descriptor.Descriptor(
  name='TradeList',
  full_name='trade.TradeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trades', full_name='trade.TradeList.trades', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TRADELIST_TRADE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=414,
)


_AGGREGATEDVALUE = _descriptor.Descriptor(
  name='AggregatedValue',
  full_name='trade.AggregatedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='trade.AggregatedValue.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=448,
)

_TRADELIST_TRADE.containing_type = _TRADELIST
_TRADELIST.fields_by_name['trades'].message_type = _TRADELIST_TRADE
DESCRIPTOR.message_types_by_name['TradeParams'] = _TRADEPARAMS
DESCRIPTOR.message_types_by_name['TradeTimeParams'] = _TRADETIMEPARAMS
DESCRIPTOR.message_types_by_name['TradeList'] = _TRADELIST
DESCRIPTOR.message_types_by_name['AggregatedValue'] = _AGGREGATEDVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeParams = _reflection.GeneratedProtocolMessageType('TradeParams', (_message.Message,), {
  'DESCRIPTOR' : _TRADEPARAMS,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:trade.TradeParams)
  })
_sym_db.RegisterMessage(TradeParams)

TradeTimeParams = _reflection.GeneratedProtocolMessageType('TradeTimeParams', (_message.Message,), {
  'DESCRIPTOR' : _TRADETIMEPARAMS,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:trade.TradeTimeParams)
  })
_sym_db.RegisterMessage(TradeTimeParams)

TradeList = _reflection.GeneratedProtocolMessageType('TradeList', (_message.Message,), {

  'Trade' : _reflection.GeneratedProtocolMessageType('Trade', (_message.Message,), {
    'DESCRIPTOR' : _TRADELIST_TRADE,
    '__module__' : 'trade_pb2'
    # @@protoc_insertion_point(class_scope:trade.TradeList.Trade)
    })
  ,
  'DESCRIPTOR' : _TRADELIST,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:trade.TradeList)
  })
_sym_db.RegisterMessage(TradeList)
_sym_db.RegisterMessage(TradeList.Trade)

AggregatedValue = _reflection.GeneratedProtocolMessageType('AggregatedValue', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDVALUE,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:trade.AggregatedValue)
  })
_sym_db.RegisterMessage(AggregatedValue)



_TRADE = _descriptor.ServiceDescriptor(
  name='Trade',
  full_name='trade.Trade',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=451,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCurrentTrades',
    full_name='trade.Trade.GetCurrentTrades',
    index=0,
    containing_service=None,
    input_type=_TRADEPARAMS,
    output_type=_TRADELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTradesAvgPrice',
    full_name='trade.Trade.GetTradesAvgPrice',
    index=1,
    containing_service=None,
    input_type=_TRADEPARAMS,
    output_type=_AGGREGATEDVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTradesAvgPriceByTime',
    full_name='trade.Trade.GetTradesAvgPriceByTime',
    index=2,
    containing_service=None,
    input_type=_TRADETIMEPARAMS,
    output_type=_AGGREGATEDVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTradesSumQuantity',
    full_name='trade.Trade.GetTradesSumQuantity',
    index=3,
    containing_service=None,
    input_type=_TRADEPARAMS,
    output_type=_AGGREGATEDVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADE)

DESCRIPTOR.services_by_name['Trade'] = _TRADE

# @@protoc_insertion_point(module_scope)
