# Generated by Django 4.1.3 on 2023-06-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_traderevenue_value_irt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderevenue',
            name='fiat_hedge_base',
        ),
        migrations.RemoveField(
            model_name='traderevenue',
            name='fiat_hedge_usdt',
        ),
    ]
