# Generated by Django 4.1.3 on 2023-07-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_delete_externalnotification'),
        ('accounting', '0025_traderevenue_value_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderevenue',
            name='login_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loginactivity'),
        ),
    ]
