# Generated by Django 4.1.3 on 2023-07-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_remove_traderevenue_base_spread_and_more'),
        ('accounting', '0026_traderevenue_login_activity'),
    ]

    operations = [
    ]
