# Generated by Django 4.1.3 on 2023-07-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_merge_20230708_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderevenue',
            name='login_activity',
        ),
    ]
