# Generated by Django 4.1.3 on 2023-07-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_merge_20230708_1636'),
        ('accounting', '0028_alter_historicalvault_type_alter_vault_type'),
    ]

    operations = [
    ]
