# Generated by Django 4.0 on 2022-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('block_date', models.DateTimeField()),
            ],
        ),
    ]
