# Generated by Django 4.0 on 2022-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktracker',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
