# Generated by Django 4.0 on 2022-01-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_blocktracker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktracker',
            name='number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
