# Generated by Django 4.0 on 2022-01-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_asset_explorer_link'),
        ('tracker', '0003_alter_blocktracker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETHBlockTracker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracker.blocktracker',),
        ),
        migrations.CreateModel(
            name='TRXBlockTracker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tracker.blocktracker',),
        ),
        migrations.AddField(
            model_name='blocktracker',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ledger.network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocktracker',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='blocktracker',
            unique_together={('number', 'network')},
        ),
    ]
